"""nfc_emulate_backend — drives the Kiisu to emulate a captured card.

PLAIN ENGLISH:
==============
You captured a Sandman keycard last week. The .nfc file is on the Kiisu's
SD card at /ext/nfc/. This backend tells the Kiisu: "be that card now."
The Kiisu starts broadcasting the captured UID + ATQA + SAK + payload
to any reader nearby. The reader sees what looks like the original card
being tapped.

TWO PATHS WE CONSIDERED:
========================
PATH A — RPC "app_start NFC" + GUI input injection
  Launch the NFC app, navigate to file, hit emulate.
  Brittle (UI changes between firmware versions, requires sleeps).

PATH B — JS runtime mission                              [CHOSEN]
  Push a tiny mJS script to /ext/apps_data/mcp/. The script imports
  Momentum's `nfc` module, calls nfc.emulate() with the source path.
  No GUI navigation. Survives firmware updates because we're calling
  the API the firmware exposes.

PATH B requires Momentum-class firmware (the operator's Kiisu runs
mntm-dev so we're good). Stock OFW operators get a clear error and
a doc link.

The mission writes a status log to /ext/apps_data/mcp_logs/ which we
read back to verify "emulation actually started" vs "JS module didn't
exist on this firmware." That's the readback contract.

NO TAGS NEEDED FOR THIS MISSION TO RUN. A reader is needed to *validate*
that emulation works against the wild — the makerspace door is exactly
that. Code paths here can be tested with the StubBackend without any
hardware.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from typing import Any, Optional, Protocol

from .sensor_backends import Detection

log = logging.getLogger("llmdr_redteam.missions.nfc_emulate_backend")


# ---------- the JS mission template -------------------------------------
# This is what gets pushed to the Kiisu. mJS syntax — string concatenation,
# no template literals, no arrow functions. Keep it boring.
#
# The script:
#   1. Imports the nfc module (Momentum-only).
#   2. Loads the saved .nfc file at SOURCE_PATH.
#   3. Calls nfc.emulate() — blocks until a stop condition.
#   4. Writes a status line to LOG_PATH so the host knows it started.
#
# Stop condition is wall-clock: nfc.emulate() takes a duration in ms.
# The host backend computes that from the timeout_s constructor arg.
#
# {SOURCE_PATH} and {LOG_PATH} and {DURATION_MS} are filled before push.

_JS_MISSION_TEMPLATE = r"""// mcp_nfc_emulate.js — push-and-run emulation mission
// Generated by llmdr_redteam.nfc_emulate_backend. Do not edit by hand.

let nfc = require("nfc");
let storage = require("storage");

let SOURCE_PATH = "{SOURCE_PATH}";
let LOG_PATH = "{LOG_PATH}";
let DURATION_MS = {DURATION_MS};

function log_line(msg) {{
    let f = storage.openFile(LOG_PATH, "a", "open_append");
    if (f) {{
        f.write(msg + "\n");
        f.close();
    }}
}}

log_line("[start] source=" + SOURCE_PATH + " duration_ms=" + DURATION_MS);

let card = nfc.parseFile(SOURCE_PATH);
if (card === null || card === undefined) {{
    log_line("[error] nfc.parseFile returned null — file missing or unparseable");
}} else {{
    log_line("[parsed] type=" + card.type + " uid=" + card.uid);
    let emulated = nfc.emulate(card, DURATION_MS);
    if (emulated) {{
        log_line("[done] emulation completed cleanly");
    }} else {{
        log_line("[stopped] emulation aborted or readers absent");
    }}
}}

log_line("[exit]");
"""


# ---------- protocol for the Flipper handle -----------------------------
# We don't import the real flipper-mcp client here — keeps this module
# importable in tests without that dependency. The duck-type protocol
# is what we need.

class _FlipperHandle(Protocol):
    storage: Any
    js: Any  # has .push(name, content) and .run(name) and .read_log(name)


# ---------- the backend -------------------------------------------------

@dataclass
class EmulateRequest:
    """What the operator hands the backend."""
    source_path: str          # /ext/nfc/sandman_room205.nfc
    duration_s: float = 30.0  # how long to broadcast


class RealNFCEmulateBackend:
    """Pushes the JS mission to the Kiisu and runs it.

    Mission code is unchanged across stub vs real — both implement
    `emulate(req: EmulateRequest) -> Detection`.

    Constructor takes a Flipper handle exposing .storage and .js (the
    flipper-mcp js_runner module). If your handle uses different attr
    names, wrap it.
    """

    sensor_name = "nfc_emulate"

    def __init__(
        self,
        flipper: Any,
        *,
        mission_name: str = "mcp_nfc_emulate",
        mission_dir: str = "/ext/apps_data/mcp",
        log_dir: str = "/ext/apps_data/mcp_logs",
        startup_grace_s: float = 1.5,
    ):
        self.flipper = flipper
        self.mission_name = mission_name
        self.mission_dir = mission_dir
        self.log_dir = log_dir
        self.startup_grace_s = startup_grace_s

    @property
    def _mission_path(self) -> str:
        return f"{self.mission_dir}/{self.mission_name}.js"

    @property
    def _log_path(self) -> str:
        return f"{self.log_dir}/{self.mission_name}.log"

    def _render_mission(self, req: EmulateRequest) -> str:
        # Literal-replace, not str.format, because the mJS template has
        # legitimate `{` / `}` braces inside JS function bodies.
        duration_ms = int(req.duration_s * 1000)
        return (
            _JS_MISSION_TEMPLATE
            .replace("{SOURCE_PATH}", req.source_path)
            .replace("{LOG_PATH}", self._log_path)
            .replace("{DURATION_MS}", str(duration_ms))
        )

    async def emulate(self, req: EmulateRequest) -> Detection:
        """Push the mission, run it, return a Detection describing what
        the Kiisu actually did.

        On success, Detection.detected=True and raw['log_tail'] holds the
        last few lines of the mission's log so the operator can see
        '[parsed] type=NTAG215 uid=...' and '[done] emulation completed'.
        """
        if self.flipper is None:
            return Detection(
                sensor="nfc_emulate", detected=False, confidence="low",
                notes="No Flipper handle — backend not connected",
            )

        # 1. Render and push the JS
        mission_src = self._render_mission(req)
        log.info("nfc_emulate: pushing %s (%d bytes)",
                 self._mission_path, len(mission_src))
        try:
            push_ok = await self._push_mission(mission_src)
        except Exception as e:
            log.exception("push failed")
            return Detection(
                sensor="nfc_emulate", detected=False, confidence="low",
                notes=f"JS push failed: {type(e).__name__}: {e}",
            )
        if not push_ok:
            return Detection(
                sensor="nfc_emulate", detected=False, confidence="low",
                notes=f"JS push to {self._mission_path} returned False — "
                      "check storage permissions",
            )

        # 2. Clear stale log so we only read THIS run's output
        await self._clear_log()

        # 3. Launch the mission. This returns immediately on Momentum;
        #    the JS app keeps running in the background.
        log.info("nfc_emulate: launching mission %r", self.mission_name)
        try:
            await self._run_mission()
        except Exception as e:
            log.exception("run failed")
            return Detection(
                sensor="nfc_emulate", detected=False, confidence="low",
                notes=f"js_run failed: {type(e).__name__}: {e}",
            )

        # 4. Wait the duration + a startup grace so the JS has time
        #    to write its [done]/[stopped] line.
        total_wait = req.duration_s + self.startup_grace_s
        log.info("nfc_emulate: waiting %.1fs for mission to finish", total_wait)
        await asyncio.sleep(total_wait)

        # 5. Read the log back, parse the status, build the Detection.
        log_text = await self._read_log()
        return self._build_detection_from_log(req, log_text)

    # ---------- the I/O hooks (overridable / mockable) ------------------

    async def _push_mission(self, src: str) -> bool:
        """Push the rendered JS to /ext/apps_data/mcp/<name>.js."""
        return await self.flipper.js.push(self.mission_name, src)

    async def _run_mission(self) -> None:
        """Launch the pushed JS mission."""
        await self.flipper.js.run(self.mission_name)

    async def _read_log(self) -> str:
        """Read back the mission's log file."""
        try:
            return await self.flipper.storage.read(self._log_path)
        except Exception as e:
            log.warning("could not read mission log %s: %s", self._log_path, e)
            return ""

    async def _clear_log(self) -> None:
        """Best-effort log clear so old runs don't pollute new readbacks."""
        try:
            await self.flipper.storage.delete(self._log_path)
        except Exception as e:
            log.debug("log clear failed (probably didn't exist): %s", e)

    # ---------- log -> Detection ---------------------------------------

    def _build_detection_from_log(
        self, req: EmulateRequest, log_text: str,
    ) -> Detection:
        """Translate the mission's [start]/[parsed]/[done]/[error] markers
        into a Detection."""
        lines = [ln.strip() for ln in (log_text or "").splitlines() if ln.strip()]
        tail = lines[-12:]  # last few lines for the operator

        if not lines:
            return Detection(
                sensor="nfc_emulate", detected=False, confidence="low",
                notes=("Mission ran but produced no log output. The nfc JS "
                       "module may be missing on this firmware (stock OFW "
                       "doesn't ship it; Momentum mntm-dev does)."),
                raw={"source_path": req.source_path, "log_tail": tail},
            )

        had_error  = any(ln.startswith("[error]")   for ln in lines)
        had_parsed = any(ln.startswith("[parsed]")  for ln in lines)
        had_done   = any(ln.startswith("[done]")    for ln in lines)
        had_stop   = any(ln.startswith("[stopped]") for ln in lines)

        # Pull uid out of the [parsed] line if we have one — that's the
        # cross-link target. "type=NTAG215 uid=04ABCDEF120000"
        emulated_uid: Optional[str] = None
        for ln in lines:
            if ln.startswith("[parsed]"):
                for part in ln.split():
                    if part.startswith("uid="):
                        emulated_uid = part.split("=", 1)[1].strip()
                        break

        if had_error:
            return Detection(
                sensor="nfc_emulate", detected=False, confidence="medium",
                notes="Mission reported [error] — see log_tail",
                raw={"source_path": req.source_path, "log_tail": tail,
                     "emulated_uid": emulated_uid},
            )

        if had_parsed and (had_done or had_stop):
            cross_link = ("nfc_uid", emulated_uid) if emulated_uid else None
            return Detection(
                sensor="nfc_emulate", detected=True, confidence="high",
                tentative_id="emulation_completed",
                cross_link=cross_link,
                notes=(
                    f"Emulated {req.source_path} for {req.duration_s:.1f}s. "
                    + ("Completed cleanly." if had_done else "Stopped early.")
                    + (f" Broadcast UID: {emulated_uid}" if emulated_uid else "")
                ),
                raw={
                    "source_path": req.source_path,
                    "emulated_uid": emulated_uid,
                    "log_tail": tail,
                    "completion": "done" if had_done else "stopped",
                },
            )

        # Mission produced log lines but never reached [parsed] or [done].
        # Most common cause: nfc module not installed on this firmware.
        return Detection(
            sensor="nfc_emulate", detected=False, confidence="low",
            notes=(
                "Mission started but did not complete the emulate cycle. "
                "Check Kiisu firmware — this mission requires Momentum's "
                "nfc JS module."
            ),
            raw={"source_path": req.source_path, "log_tail": tail},
        )


# ---------- stub backend for tests --------------------------------------

class StubNFCEmulateBackend:
    """In-memory stub. Configure with a canned log; mission code drives it
    exactly like the real backend would."""

    sensor_name = "nfc_emulate"

    def __init__(self, canned_log: str = "", canned_uid: Optional[str] = None):
        self.canned_log = canned_log
        # canned_uid is unused for now — log_tail parser pulls UID from the
        # [parsed] line — but we expose it so future tests can short-circuit.
        self.canned_uid = canned_uid
        self.received_requests: list[EmulateRequest] = []

    async def emulate(self, req: EmulateRequest) -> Detection:
        self.received_requests.append(req)
        # Reuse the real backend's parser by instantiating it briefly.
        proxy = RealNFCEmulateBackend(flipper=None)
        return proxy._build_detection_from_log(req, self.canned_log)


# ---------- canned logs for stub fixtures -------------------------------

CANNED_LOG_SUCCESS = (
    "[start] source=/ext/nfc/sandman_room205.nfc duration_ms=30000\n"
    "[parsed] type=NTAG215 uid=04abcdef120000\n"
    "[done] emulation completed cleanly\n"
    "[exit]\n"
)

CANNED_LOG_STOPPED_EARLY = (
    "[start] source=/ext/nfc/sandman_room205.nfc duration_ms=30000\n"
    "[parsed] type=NTAG215 uid=04abcdef120000\n"
    "[stopped] emulation aborted or readers absent\n"
    "[exit]\n"
)

CANNED_LOG_PARSE_FAIL = (
    "[start] source=/ext/nfc/missing.nfc duration_ms=30000\n"
    "[error] nfc.parseFile returned null — file missing or unparseable\n"
    "[exit]\n"
)

CANNED_LOG_EMPTY = ""

CANNED_LOG_NO_NFC_MODULE = (
    # What stock OFW would write if `require("nfc")` itself failed —
    # but actually it would crash before writing anything. We model
    # that as empty log.
    ""
)
